<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/06/21 12:36:24
sfConfig::add(array(
  'app_sf_guard_plugin_success_signin_url' => '/adminBlog',
  'app_sf_guard_plugin_success_signout_url' => '/adminBlog',
  'app_title_login' => 'Administrador Blog',
  'app_post_content_long' => 200,
  'app_mp_reality_admin_bloc00' => array (
  0 => 
  array (
    0 => 'Administrador',
    1 => 'Editor',
  ),
),
  'app_mp_reality_admin_bloc01' => array (
  0 => 
  array (
    0 => 'Administrador',
    1 => 'Editor',
  ),
),
  'app_mp_reality_admin_bloc02' => array (
  0 => 
  array (
    0 => 'Administrador',
    1 => 'Editor',
  ),
),
  'app_mp_reality_admin_bloc03' => array (
  0 => 
  array (
    0 => 'Autor',
    1 => 'Colaborador',
  ),
),
  'app_mp_reality_admin_bloc04' => array (
  0 => 
  array (
    0 => 'Autor',
    1 => 'Colaborador',
  ),
),
  'app_mp_reality_admin_bloc05' => array (
  0 => 
  array (
    0 => 'Autor',
    1 => 'Colaborador',
  ),
),
  'app_mp_reality_admin_bloc10' => array (
  0 => 
  array (
    0 => 'Administrador',
    1 => 'Editor',
    2 => 'Autor',
    3 => 'Colaborador',
  ),
),
  'app_mp_reality_admin_bloc11' => array (
  0 => 
  array (
    0 => 'Administrador',
    1 => 'Editor',
    2 => 'Autor',
    3 => 'Colaborador',
  ),
),
  'app_mp_reality_admin_bloc12' => array (
  0 => 
  array (
    0 => 'Administrador',
    1 => 'Editor',
    2 => 'Autor',
    3 => 'Colaborador',
  ),
),
  'app_mp_reality_admin_bloc20' => array (
  0 => 
  array (
    0 => 'Administrador',
    1 => 'Editor',
  ),
),
  'app_mp_reality_admin_bloc21' => array (
  0 => 
  array (
    0 => 'Administrador',
    1 => 'Editor',
  ),
),
  'app_mp_reality_admin_web_dir' => '/mpRealityAdminPlugin',
  'app_mp_reality_admin_image_dir' => '/images/',
  'app_mp_reality_admin_use_jquery' => true,
  'app_mp_reality_admin_css_reset' => false,
  'app_mp_reality_admin_max_per_page' => array (
  0 => '3',
  1 => '5',
  2 => '10',
  3 => '20',
  4 => '50',
  5 => '100',
  6 => '∞',
),
  'app_mp_reality_admin_categories' => array (
  'Bloc1' => 
  array (
    'label' => 'Post',
    'class' => 'medium',
    'items' => 
    array (
      'Borrador' => 
      array (
        'url' => '/adminBlog/post?state=dr',
        'image' => 'draft.png',
        'badge' => 
        array (
          'model' => 'Post',
          'table_method' => 'getDraft',
        ),
      ),
      'Publicados' => 
      array (
        'url' => '/adminBlog/post?state=pu',
        'image' => 'publish.png',
        'badge' => 
        array (
          'model' => 'Post',
          'table_method' => 'getPublished',
        ),
      ),
      'Pendientes' => 
      array (
        'url' => '/adminBlog/post?state=pe',
        'image' => 'pending.png',
        'badge' => 
        array (
          'model' => 'Post',
          'table_method' => 'getPending',
        ),
      ),
      'Tus Borradores' => 
      array (
        'url' => '/adminBlog/post?state=dr',
        'image' => 'draft.png',
        'badge' => 
        array (
          'model' => 'Post',
          'table_method' => 'getDraftUser',
        ),
      ),
      'Tus Publicaciones' => 
      array (
        'url' => '/adminBlog/post?state=pu',
        'image' => 'publish.png',
        'badge' => 
        array (
          'model' => 'Post',
          'table_method' => 'getPublishedUser',
        ),
      ),
      'Tus Pendientes' => 
      array (
        'url' => '/adminBlog/post?state=pe',
        'image' => 'pending.png',
        'badge' => 
        array (
          'model' => 'Post',
          'table_method' => 'getPendingUser',
        ),
      ),
    ),
  ),
  'Bloc2' => 
  array (
    'label' => 'Comentarios',
    'class' => 'medium',
    'items' => 
    array (
      'Pendientes' => 
      array (
        'url' => '/adminBlog/comment?state=pe',
        'image' => 'comment.png',
        'badge' => 
        array (
          'model' => 'Comment',
          'table_method' => 'getCommentPending',
        ),
      ),
      'Publicados' => 
      array (
        'url' => '/adminBlog/comment?state=pu',
        'image' => 'comment.png',
        'badge' => 
        array (
          'model' => 'Comment',
          'table_method' => 'getCommentPublic',
        ),
      ),
      'Comentarios de Hoy' => 
      array (
        'url' => '/adminBlog/comment?state=now',
        'image' => 'comment.png',
        'badge' => 
        array (
          'model' => 'Comment',
          'table_method' => 'getCommentDay',
        ),
      ),
    ),
  ),
  'Bloc3' => 
  array (
    'label' => 'Estadísticas',
    'class' => 'medium',
    'items' => 
    array (
      'Visitas' => 
      array (
        'url' => '/adminBlog/comment/statisticsPost',
        'image' => 'chart.png',
      ),
      'Comentarios' => 
      array (
        'url' => '/admin/comment/statisticsComment',
        'image' => 'chart.png',
      ),
    ),
  ),
),
));
