<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/06/21 12:36:24

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=repo',
  'username' => 'root',
  'password' => 'caronates/recytics',
  'name' => 'doctrine',
)),);
