<?php

/**
 * Post
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    shimano
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Post extends BasePost {

    public function getUsuario() {
        return $this->getSfGuardUser()->getFirst();
    }
    public function getCategoriesList(){
        return Doctrine::getTable('PostCategory')->findByPostId($this->getId());
    }
    public function getTagsList(){
        return Doctrine::getTable('PostTag')->findByPostId($this->getId());
    }
    public function getCommentAmonut(){
        return Doctrine::getTable('Comment')->findByPostId($this->getId());
    }
    public function getCountComment($id) {
        $q=Doctrine::getTable('Comment')->findByPostId($id);
        return $q->count();
    }
    
}
