<?php

/**
 * VisitTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VisitTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object VisitTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Visit');
    }

    public function save($id,Doctrine_Connection $conn = null) {

        $conn = Doctrine_Manager::connection();
        $conn->transaction->setIsolation('SERIALIZABLE');
        $conn->beginTransaction();
        try {

            $visita = new Visit();
            $visita->setIp($_SERVER["REMOTE_ADDR"]);
            $visita->setDate(date('Y-m-d'));
            $visita->setPostId($id);
            $visita->save($conn);
           
            $conn->commit();
        } catch (Doctrine_Exception $e) {
            $conn->rollback();
            return null;
        }
    }

}